ecs_pod.go, ecs_pod_creator.go, mock/ecs_pod.go, mock/ecs_pod_creator.go, mock/mock_test.go
Jira: https://jira.mongodb.org/browse/EVG-14808
* Convert `ECSPod` into an interface for easier mockability and to allow alternative implementations.
* Add constructor for `BasicECSPod`.
* Add more metadata fields that will be relevant to `ECSPod`s.
=> EVG-14808: add more boilerplate code for pod and pod creator

awsutil/client_options.go, awsutil/client_options_test.go
Jira: https://jira.mongodb.org/browse/EVG-14841
Make the access credentials optional as long as a role is given. Build should have configured the app server's EC2 instances to allow us to assume the correct role without passing any credentials to STS (as long as the call to STS is made from Evergreen's app servers). This means that the app server can call `AssumeRole` to get authorized credentials to use ECS/Secrets Manager without passing in any initial access key or secret access key and we don't have to store/manage AWS keys anymore.
=> EVG-14841: make credentials optional if role is set

mock/mock_test.go, mock/secrets_manager_client.go, mock/secrets_manager_client_test.go
Jira: https://jira.mongodb.org/browse/EVG-14861
* Implement mock Secrets Manager service, which behaves similar to an actual Secrets Manager service but for testing.
* Implement mock Secrets Manager client, which is backed by the mock Secrets Sanager service (but can be modified to not use it as well).
* Test mock Secrets Manager client/service against Secrets Manager test cases.
=> EVG-14861: implement mock secrets manager

ecs/client_test.go, glide.lock, internal/testcase/ecs_client.go, mock/ecs_client.go, mock/ecs_client_test.go, mock/mock_test.go, mock/secrets_manager_client.go, mock/secrets_manager_client_test.go, vendor/github.com/evergreen-ci/utility/optional.go
Jira: https://jira.mongodb.org/browse/EVG-14860
* Implement mock ECS service that just stores payloads in some in-memory data structures.
* Implement mock ECS client that stores input and returns stub output if specified. Otherwise, it interacts with the mock ECS service to access/modify the stored metadata about tasks. 
* Test the mock ECS client against the same tests as the real implementation to verify correctness.
* Upgrade github.com/evergreen-ci/utility.
=> EVG-14860: implement mock ECS client

internal/testcase/secrets_manager_vault.go, mock/mock_test.go, mock/secrets_manager_vault_test.go, mock/vault.go, secret/secrets_manager_client.go, secret/secrets_manager_vault.go, secret/secrets_manager_vault_test.go, vault.go
JIra: https://jira.mongodb.org/browse/EVG-14857
* Implement a mock Vault which can be backed by any other Vault implementation by default. In my case, I just tested the mock using the actual Secrets Manager Vault implementation with a mock Secrets Manager client to fake out the actual Secrets Manager service.
* Refactor Secrets Manager Vault tests into the common testcase package.
* Make some minor error-checking fixes to the Secrets Manager Vault implementation.
=> EVG-14857: implement mock vault

ecs/client_test.go, ecs/pod.go, ecs/pod_creator.go, ecs/pod_creator_test.go, ecs/pod_test.go, ecs_pod.go, ecs_pod_creator.go, ecs_pod_creator_test.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, mock/ecs_pod_test.go, secret/secrets_manager_vault_test.go
Jira: https://jira.mongodb.org/browse/EVG-15027
* Rename pod status enum values slightly.
* Remove duplicate `SetName` when updating the secret name from the friendly alias to the ARN.
* Add comment on why the secret name has to be updated.
* Add `SetOwned` for `SecretOptions`.
* Fix up a bunch of tests that depend on common shared structs which could lead to inter-test dependencies.
=> EVG-15027: fix up miscellaneous minor issues

ecs/pod.go, ecs/pod_creator.go, ecs/pod_test.go, ecs_pod.go, ecs_pod_creator.go, ecs_pod_creator_test.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go
Jira: https://jira.mongodb.org/browse/EVG-15098
Rename enums to use type prefixes instead of type suffixes for consistency and to make autocomplete easier.
=> EVG-15098: rename enums to be type-prefixed instead of type-suffixed

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-15108
* Add working directory as a parameter to the container definition.
* Remove tags from the container definition since container definitions can't be tagged.
* Move execution role to the creation options instead of execution options because it must be set when the task definition is first registered.
* Add mock tests to verify that the inputs from the ECS pod creator to the ECS/Secrets Manager API are mapped correctly.
* Fix some small copy-pasting bugs in the ECS pod creator implementation.
=> EVG-15108: add working directory container option

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-14962
Add an option to constrain placement of pods to a subset of all available hosts in the cluster using the ECS cluster query language. This is useful for things like enforcing single-tenant pods.
=> EVG-14962: add container instance filter queries

ecs/pod.go, ecs/pod_creator.go, ecs/pod_creator_test.go, ecs/pod_test.go, internal/testcase/ecs_pod.go, mock/ecs_client.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_test.go, mock/secrets_manager_client.go
Jira: https://jira.mongodb.org/browse/EVG-15034
* Make stop and delete idempotent operations.
* Do more to clean up resources in ECS created by tests.
* Allow the mock clients to return fake errors.
=> EVG-15034: make stop and delete idempotent

ecs/pod.go, ecs/pod_creator.go, ecs/pod_test.go, ecs_pod.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, mock/ecs_pod.go, mock/ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-15128
I split the info method for separation of concerns since we might want to get resources without getting the status and vice versa - I originally wrote the info method and combined the two just for convenience, but it makes sense to keep them separate. It also makes it easier to organize information when the statuses include both the aggregate pod status and each individual container's status (which will be done in a later ticket).
=> EVG-15128: split pod info into resources and status

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, ecs_pod_test.go, internal/testcase/ecs_pod_creator.go
Jira: https://jira.mongodb.org/browse/EVG-15116
Add support for storing and using image repository credentials for each container when creating new pods. ECS only supports two ways of authenticating: either having the AMI include repository credentials information or reading credentials from Secrets Manager.
I tested the new repository credentials and also added some tests for unrelated features for better coverage.
=> EVG-15116: add repository credentials to ECS pod creation options

ecs/pod.go, ecs/pod_creator.go, ecs/pod_creator_test.go, ecs/pod_test.go, ecs_pod.go, ecs_pod_creator.go, ecs_pod_test.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, mock/ecs_client.go, mock/ecs_pod.go, mock/ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-15104
* Expose container-level information about pods. Container ARNs is available in the resource information and container-level statuses are availabe in the status information, which are associated with the container names that users can provide as input. Secrets are now tied to individual containers rather than the pod as a whole.
* Refactors some structs to reflect new assumptions that secrets are per-container and containers have their own statuses.
* Test new container-level information.
* Clean up some copy-pasting within tests.
=> EVG-15104: expose container-level information in pods

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, internal/testcase/ecs_pod_creator.go
Jira: https://jira.mongodb.org/browse/EVG-15174
* Add options to set pod networking mode and container port mappings.
* Refactor some ECS glue code conversion functions in the ECS package so that they're methods on the pod creator instead of plain functions.
* Slightly improve existing test coverage.
=> EVG-15174: add pod network settings

ecs_pod.go, ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-15104
I forgot to add the unknown status as a valid status. This is considered a valid state because we might legitimately not know or keep track of the current state of a container (e.g. the network is down, so we can't verify what state it's in). Statuses for containers are also optional, for which unknown is the valid indeterminate state.
=> EVG-15104: validate unknown ECS status

ecs/pod.go, ecs/pod_creator.go, ecs/pod_test.go, ecs_pod.go, ecs_pod_creator.go, ecs_pod_creator_test.go, ecs_pod_test.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, mock/ecs_pod_creator.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-15139
* Make a field to distinguish between the secret's friendly name and the unique ARN assigned after the secret is created in Secrets Manager. ECS pods should always perform Secrets Manager operations with the unique ID. The name is just a useful piece of information to associate the friendly secret names that the user gave with the final ARN associated with the created secret. That way, if the user passes a friendly secret name and asks it to be created, they can map the secret name they requested to the unique ARN.
* Propagate the secret name and secret ID (after the secret is created) to the ECS pod's resources during pod creation. I had to make some intermediate structs to hold temporary information until all the secrets were created in …
=> EVG-15139: include secret IDs in ECS pod after creation

ecs/client_test.go, ecs/pod_creator_test.go, ecs/pod_test.go, internal/testcase/ecs_client.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, internal/testcase/secrets_manager_client.go, internal/testcase/vault.go, internal/testutil/aws.go, internal/testutil/ecs.go, internal/testutil/secret.go, mock/ecs_client_test.go, mock/ecs_pod_test.go, mock/secrets_manager_client.go, secret/secrets_manager_client.go, secret/secrets_manager_client_test.go, secret/secrets_manager_vault_test.go, secrets_manager_client.go
Jira: https://jira.mongodb.org/browse/EVG-14979
* During teardown, clean up all task definitions, tasks, and secrets that were created during that test.
* Cleaning up the resources are tricky because we have to avoid the possibility that the cleanup interferes with another running instance of that test. For example, if cleanup is happening on your local machine for `TestECSClient` and at the same time, a CI machine is running `TestECSClient`, the cleanup mechanism should not affect the CI test at all. I resolved this by adding a random string generated at runtime to distinguish between test runtime instances. The resources will only be cleaned up if the runtime random string appears in the ARN.
* Cleaning up tasks is also tricky because we have no control over the task's ARN. Both task …
=> EVG-14979: clean up ECS and Secrets Manager resources during test teardown

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, mock/ecs_client.go, mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-15378
Add support for ECS task groups. By default, ECS tasks are assigned to hosts independently of one another. Task groups are a feature that lets the user have more control over how tasks in the task group are assigned to hosts.
=> EVG-15378: add support for pod placement groups

ecs/pod_creator.go, ecs_pod_creator.go, mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-15378
This is a follow-on feature to #46. If ECS tasks are in the same ECS task group, they can be given a special placement constraint that ensures that they will be assigned to different instances. This can be used to enforce that ECS tasks in the same task group each get their own instance to run in.
=> EVG-15378: support placing pods in the same group on distinct instances

awsutil/client_options_test.go, ecs/client_test.go, ecs/pod.go, ecs/pod_creator.go, ecs/pod_creator_test.go, ecs/pod_test.go, ecs_pod.go, internal/testcase/ecs_pod.go, mock/ecs_client.go, mock/ecs_client_test.go, mock/ecs_pod.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_test.go, mock/secrets_manager_client_test.go, mock/secrets_manager_vault_test.go, secret/secrets_manager_client_test.go, secret/secrets_manager_vault_test.go
Jira: https://jira.mongodb.org/browse/EVG-15161
* Add `LatestStatusInfo` method for pods to get status info directly from ECS rather than cached status.
* Use test timeout constants.
=> EVG-15161: add method to get latest pod status

cmd/verify-mod-tidy/verify-mod-tidy.go, evergreen.yaml, go.mod, makefile
Jira: https://jira.mongodb.org/browse/EVG-15448
Add a helper Go script and CI task to check if go mod tidy has been run, which is important for keeping the go.mod and go.sum clean. If it hasn't been run, the make target and CI task will fail. I ran it locally to check that it works as expected.
=> EVG-15448: add check for mod tidy

ecs/client.go
Jira: https://jira.mongodb.org/browse/EVG-16562
Fix an issue where logging an AWS API error mutates the `message.Fields`, causing the message to spuriously show an error on the successful retry.
=> EVG-16562: do no reuse AWS API log message between retries

ecs/client_test.go, ecs/status.go, internal/testcase/ecs_client.go, mock/ecs_client.go, mock/ecs_client_test.go
Jira: https://jira.mongodb.org/browse/EVG-16877
This is some boilerplate code for the actual features related to container instances. When we get an SNS notification that a container instance (i.e. an EC2 instance running tasks in ECS) is going to be interrupted, we need to check its status and if the instance status is `"DRAINING"`, use `ListTasks` to get the ECS tasks currently running on that container instance. This will help us figure out which ECS tasks are going to be abruptly stopped by spot instance interruption.
* Add constants for ECS container instance statuses.
* Add tests for `ListTasks` and improve fake ECS service.
=> EVG-16877: support ListTasks and add container instance statuses

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, mock/ecs_client.go, mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-17026
Build changed the way the cluster infrastructure is set up, which also necessitates us changing how we configure pods. Before, we used a single capacity provider and chose an instance with the correct CPU architecture for the container by specifying [placement constraints](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html). They changed it so that we use multiple [capacity providers](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-capacity-providers.html), each of which maps to an AMI that runs an instance with a particular CPU architecture. This adds support for specifying which capacity provider the pod should use so that we can still have the pod run on a the targeted …
=> EVG-17026: add option to set pod capacity provider

ecs/client.go, ecs/client_test.go, ecs/pod.go, ecs/pod_creator.go, error.go, error_test.go, internal/testcase/ecs_client.go, mock/ecs_client.go, mock/ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-17170
The ECS SDK returns either an error or a failure response indicating that the task cannot be found in ECS if the task either doesn't exist or the task has been stopped for a long time and ECS no longer has information about it. It seems like for API calls that require you to specify a single task ARN (like [`StopTask`](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#StopTaskInput)), it will return an error when the task cannot be found; for API calls that allow you to pass many task ARNs (like `DescribeTasks`), it will return nil error and will instead populate the [`Failures` field in the response](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#DescribeTasksOutput) with one failure for each task that it cannot find.
* Add …
=> EVG-17170: handle error due to missing task

ecs/pod_creator.go, ecs/pod_definition_cache.go, ecs_pod_creator.go, ecs_pod_creator_test.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-16890
* Set up the interface by which we can manage the lifecycle of cloud pod definitions and cache them (i.e. CRUD them in the DB). For now, there's only one method to create a pod definition, but we'll need to add more methods for other functionality like deleting later on. The implementation is going to be filled in as part of [EVG-16891](https://jira.mongodb.org/browse/EVG-16891).
* Refactor the `ECSPodCreationOptions` so that we can pass the pod definition options as an independent struct (`ECSPodDefinitionOptions`) to the pod definition manager. The `ECSPodCreationOptions` is supposed to both create the pod definition and run it; we need to isolate the first step of just creating the pod definition from some inputs so that the pod …
=> EVG-16890: set up pod definition manager and cache

ecs/pod_test.go, ecs_pod_creator.go, ecs_pod_creator_test.go, mock/ecs_client.go
Jira: https://jira.mongodb.org/browse/EVG-16911
Add a `Hash` function to compute the hash digest of the pod definitions, which is [based on Cedar's hash-based ID generation](https://github.com/evergreen-ci/cedar/blob/346b0b2bdaa508a5c3b78b3f4d3e2dbc2c17dd1e/model/buildlogger.go#L365-L402). Evergreen needs to be able to quickly compute the hash for pod definitions, because it needs to be able to easily determine whether or not a pod definition is already present in its cache (i.e. in the DB) based on all the inputs given when registering the definition in ECS. Cache hits/misses are based on whether a pod definition in the cache with an identical hash already exists. The hashing should work such that if two pod definitions have the same hash, then they will run identical pods when `RunTask` …
=> EVG-16911: compute hash digest for pod definitions

doc.go, ecs/pod_creator.go, ecs/pod_creator_test.go, ecs/pod_definition_manager.go, ecs/pod_definition_manager_test.go, ecs/pod_test.go, internal/testcase/ecs_client.go, internal/testcase/secrets_manager_client.go, internal/testutil/secret.go, internal/testutil/secret_cache.go, mock/ecs_client.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_definition_manager_test.go, mock/ecs_pod_test.go, mock/secret_cache.go, mock/secret_cache_test.go, mock/secrets_manager_client.go, mock/secrets_manager_vault_test.go, mock/vault_test.go, secret/secrets_manager_client.go, secret/secrets_manager_vault.go, secret/secrets_manager_vault_test.go, secret_cache.go, secrets_manager_client.go, vault.go
Jira:
https://jira.mongodb.org/browse/EVG-16896
https://jira.mongodb.org/browse/EVG-16897
This is similar to the pod definition cache #77 in terms of implementation/interface. We want to be able to externally store secrets after they're created (in the DB) so that secret values like repo creds in ECS can be tracked in the DB.
* Add interface for attaching optional secret cache to the Secrets Manager vault implementation.
* Implement `TagResource` API call for Secrets Manager to keep track of whether secrets are tracked or not.
* Add mock implementation of secret cache for testing purposes.
* Add tests for secret caching behavior. Also tidy up a couple of the existing tests.
=> EVG-16896, EVG-16897: add means to cache secrets

mock/ecs_client.go
Jira: https://jira.mongodb.org/browse/EVG-16894
Set the execution role in the mock ECS service when it's provided during task registration.
=> EVG-16894: include execution role in mock ECS service

ecs/pod_definition_manager.go, ecs_pod_definition_manager.go, internal/testutil/ecs_pod_definition_cache.go, mock/ecs_pod_definition_cache.go, mock/ecs_pod_definition_manager_test.go
Jira: https://jira.mongodb.org/browse/EVG-16892
Add a method to the Secrets Manager vault to support deleting pod definitions.
=> EVG-16892: support deleting cached pod definitions

internal/testutil/secret_cache.go, mock/ecs_pod_definition_manager_test.go, mock/secret_cache.go, mock/secrets_manager_vault_test.go, secret/secrets_manager_vault.go, secret_cache.go
Jira: https://jira.mongodb.org/browse/EVG-16899
When deleting a secret (in Secrets Manager), also delete it from the cache.
=> EVG-16899: support deleting cached secrets

mock/ecs_pod_definition_manager.go
Jira: https://jira.mongodb.org/browse/EVG-16900
Add the mockable method for deleting a pod definition.
=> EVG-16900: add mock method to delete pod definition

awsutil/base_client.go, awsutil/client_options_test.go, doc.go, ecs/client.go, ecs/client_test.go, ecs/pod_creator_test.go, ecs/pod_definition_manager_test.go, ecs/pod_test.go, internal/testcase/ecs_client.go, internal/testcase/tag_client.go, internal/testutil/aws.go, internal/testutil/secrets_manager.go, makefile, mock/ecs_client.go, mock/ecs_pod_creator_test.go, mock/secrets_manager_client.go, mock/tag_client.go, mock/tag_client_test.go, secret/secrets_manager_client.go, secret/secrets_manager_vault_test.go, tag.go, tag/client.go, tag/client_test.go, tag/doc.go
Jira: https://jira.mongodb.org/browse/EVG-17398
* Add client for Resource Groups Tagging API. `GetResources` is a useful call to filter for AWS resources using tags, which is going to be used to find Evergreen-created resources.
* Refactor the other AWS clients to use more common base functionality in the `BaseClient` and use common test helpers for AWS-related setup.
* Add fake in-memory implementation for the tag client, which can only filter for secrets in Secrets Manager and task definitions in ECS.
* Clean up a couple tests.
=> EVG-17398: implement resource tag client

ecs/client.go, ecs/client_test.go, ecs/pod.go, ecs/pod_creator.go, evergreen.yaml, go.mod, go.sum, internal/testcase/ecs_client.go, internal/testcase/ecs_pod.go, internal/testcase/ecs_pod_creator.go, internal/testutil/ecs.go, internal/testutil/env.go
Jira: https://jira.mongodb.org/browse/EVG-17754
* Add retries for errors that occur due to transient problems in ECS (due to waiting to scale out).
* Include capacity provider with `RunTask` requests because the cluster infrastructure no longer has a default capacity provider.
=> EVG-17754: retry for transient ECS-side errors

ecs/client.go, ecs/client_test.go, ecs/pod.go, ecs/pod_creator.go, ecs/pod_creator_test.go, ecs/pod_definition_manager_test.go, ecs/pod_test.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_test.go
Jira: https://jira.mongodb.org/browse/EVG-17270
Idiomatic Go code tries to avoid [stutter](https://sben.dev/stutter/) in naming, which is basically redundantly repeating the package name again in the types/functions/methods within the package (e.g. `ecs.BasicECSClient`). This is just a rename of the types to reduce the stuttering in the `ecs` package - it's already obvious enough that it's an ECS construct if it's taken from the `ecs` package.
=> EVG-17270: remove redundant ECS naming from ECS package

ecs/pod_definition_manager.go, ecs/pod_definition_manager_test.go, ecs_pod_definition_cache.go, ecs_pod_definition_manager.go, internal/testutil/ecs_pod_definition_cache.go, internal/testutil/secret_cache.go, mock/ecs_pod_definition_cache.go, mock/ecs_pod_definition_manager_test.go, mock/secret_cache.go, mock/secrets_manager_vault_test.go, secret/secrets_manager_vault.go, secret/secrets_manager_vault_test.go, secret_cache.go
Jira: https://jira.mongodb.org/browse/EVG-17516
Refactor the cache tag parameter out of the Secrets Manager/ECS manager construction options and into the cache tag interface since the tag is only relevant if the cache is being used. There's no logical change here, just moving a field elsewhere.
=> EVG-17516: refactor cache tag into method

ecs/client.go, ecs/client_test.go, ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, internal/testcase/ecs_pod_creator.go, internal/testcase/ecs_pod_definition_manager.go, mock/ecs_client.go, mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-18036
This exposes a feature in the ECS SDK that will alleviate the issues where Evergreen is not reusing the same pod definition. The issue there is that the `POD_ID` environment variable is unique for each newly-created pod, so each pod definition ends up being different for each pod.
We can work around this by setting the `POD_ID` environment variable when running the pod instead of when registering its definition. `RunTask` offers [options to explicitly override the settings that were set when the definition was registered](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#TaskOverride). This PR makes the necessary changes to the Cocoa API so that callers can set the overriding values when running the task.
* Add settings to override pod …
=> EVG-18036: support pod override options

ecs_pod_creator.go
[EVG-18305](https://jira.mongodb.org/browse/EVG-18305)
Now that we've moved environment variables to the override options, the [MergeECSPodExecutionOptions](https://github.com/evergreen-ci/cocoa/blob/main/ecs_pod_creator.go#L1233) needs to respect the OverrideOpts as well.
Tested in staging.
=> EVG-18305: Add overrides to ECS options merge function

ecs/pod_creator.go, ecs_pod_creator.go, ecs_pod_creator_test.go, mock/ecs_pod_creator_test.go
https://jira.mongodb.org/browse/EVG-19155
This adds a `LogConfiguration` parameter in our container definitions that is meant to follow the standard defined in the [AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html) to enable logging for our ECS cluster
* Added hashing and validation to the new `LogConfiguration` struct
* Tested originally with some hardcoded values and confirmed container logs are now viewable in AWS. Will make a separate Evergreen-side PR to make this more flexibly configurable as well.
=> EVG-19155: Add log configurations to container definitions

awsutil/base_client.go, awsutil/client_options.go, awsutil/client_options_test.go, ecs/client.go, ecs/client_test.go, ecs/pod_creator_test.go, ecs/pod_definition_manager_test.go, ecs/pod_test.go, ecs_client.go, internal/testutil/aws.go, mock/ecs_client.go, mock/ecs_client_test.go, mock/ecs_pod_creator_test.go, mock/ecs_pod_definition_manager_test.go, mock/ecs_pod_test.go, mock/secrets_manager_client.go, mock/secrets_manager_client_test.go, mock/secrets_manager_vault_test.go, mock/tag_client.go, mock/tag_client_test.go, secret/secrets_manager_client.go, secret/secrets_manager_client_test.go, secret/secrets_manager_vault_test.go, secrets_manager_client.go, tag.go, tag/client.go, tag/client_test.go
[DEVPROD-6951](https://jira.mongodb.org/browse/DEVPROD-6951)
In CloudTrail there still are sporadic bursts of STS calls that I think are attributable to the pod lifecycle. This PR caches the `aws.Config` in memory so we don't incur a call to STS for each call to NewBasicClient/NewBasicSecretsManagerClient/MakeTagClient.
Caching required that we use the same HTTP client each time instead of fetching a new one from the pool. This seems okay since we'll be caching the config so we'll always use the same HTTP client for all the calls. Once fetching a client from the pool was removed, the chain of `Close()` functions became extraneous so they were removed.
An alternative to all of this could be to cache the Basic/SecretsManager/Tag clients where we get them in Evergreen (e.g. …
=> DEVPROD-6951 cache AWS config
